### ISSUE TITLE
Not working with meet.jit.si recently 

### ISSUE THREAD

**Issue by bhatvv** [Teamxrtc/MeetRTC_iOS#2]

**Comment by nguyenvanminh88** [comment]
Sorry but I have problem compiling xcode.
I don't know how to build static library "Build MeetRTCSDK to build MeetRTCSDK static library."
So when I run MeetRTC it showed up this bug:
Undefined symbols for architecture x86_64:
```
  "_OBJC_CLASS_$_WebRTCSessionConfig", referenced from:
      objc-class-ref in MRTCVideoViewController.o
  "_OBJC_CLASS_$_WebRTCStack", referenced from:
      objc-class-ref in MRTCVideoViewController.o
  "_OBJC_CLASS_$_WebRTCStackConfig", referenced from:
      objc-class-ref in MRTCVideoViewController.o
  "_OBJC_CLASS_$_WebRTCStreamConfig", referenced from:
      objc-class-ref in MRTCVideoViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)``
```
Is it wrong because I haven't build libMeetRTCSDK.a. Sorry it's the first time I compile xcode so everything is new for me? Thanks.

**Comment by nguyenvanminh88** [comment]
I run it on iPad, build static library from MeetRTCSDK, put it under MeetRTC/libs and launch MeetRTC on iPad but there's nothing happened. Have some warning instead in:
```
MRTCVideoViewController.m
Main.storyboard
Asset.xcassets

```
What's the problem here?

**Comment by bhatvv** [comment]
Could you try  iPhone5s or higher also  let us know what version of the iPad

**Comment by nguyenvanminh88** [comment]
I tried on iPhone 6 running iOS 9.1. Also built on iPad 2 WIFI.
I even tried to launch on simulator.

Nguyen Van Minh
Telecommunication Engineering - Politecnico di Milano
Mobile: +393892011307

**Comment by bhatvv** [comment]
@nguyenvanminh88   Give a try now with latest master.

**Comment by nguyenvanminh88** [comment]
I will give it a try and reply soon.
Thanks!

Nguyen Van Minh
Telecommunication Engineering - Politecnico di Milano
Mobile: +3892011307

**Comment by nguyenvanminh88** [comment]
@bhatvv It works with iPhone 6 ios 8.4 right now. I will try something else. Regards :+1:

**Comment by nguyenvanminh88** [comment]
There are some problems during calling session now:
- audio: sometimes it's confused with speaker phone and integrated phone.
- session: I think the server doesn't recognise correctly "closing signal". Then sometimes, after leaving the room and coming back, the room will show one more dark icon (if there is actually 2 people in the room, now it displays one more dark icon -> 3 icons in the list). It makes connection not stable.
Is there any chances that you can fix it?
I would very appreciate this because I've tried to contact to jitsi community asking for protocols but they haven't answered yet. Since I couldn't understand the protocol on meet jitsi so I can't do anything so far.

**Comment by bhatvv** [comment]
@nguyenvanminh88 
audio: sometimes it's confused with speaker phone and integrated phone. 
-- audio is now in integrated ear speaker instead of  loud speaker from WebrRTC Stack V48 by default 
session issue will look into it

**Comment by bhatvv** [comment]
Closing this as main issue has been addressed.
